name: Go

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: tdengine/tdengine-beta:latest
      options: --user root
      volumes:
        - /etc/apt/sources.list:/etc/apt/sources.list
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: start taosd
        run: nohup taosd &

      - name: Install build-essential
        run: apt-get update && apt-get install -y build-essential curl

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...